### ISSUE TITLE
Please add itsabouttime.py to this repo

### ISSUE THREAD

**Issue by cclauss** [ruudvanderham/itsabouttime#1]
It would be interesting to update itsabouttime to take advantage of the ui module.

**Comment by ruudvanderham** [comment]
It's on my list. Stay tuned.
I have done some work with new ui: a program to convert a number in base
between 2 and 36 to another base between 2 and 36. It involves three
keyboards at the same time. I will publish it in due course.

Ruud

On Sunday, July 13, 2014, cclauss notifications@github.com wrote:

> It would be interesting to update itsabouttime to take advantage of the ui
> module.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/upwart/itsabouttime/issues/1.

## 

Ruud van der Ham
_rt.van.der.ham@gmail.com rt.van.der.ham@gmail.com_

**Comment by cclauss** [comment]
Can you please add itsabouttime.py to this repo?
